config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
 
  resources :hosts do 
   resources :workspaces
  end 

  resources  :users

  resources  :workspaces

  
  #Routes for creating(listing)/searching for workspace 
  get 'list' , to: 'workspaces#new'
  post 'list', to: 'workspaces#create'
  get 'search', to: 'workspaces#index'
  # get 'edit' , to: 'workspaces#'
   

  #User Signup routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #Host Signup routes
  get '/signuphost', to: 'hosts#new'
  post '/signuphost', to: 'hosts#create'
  get 'dashboard' , to: 'host#index'

  #User Login routes
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  #Host Login routes
  get '/loginhost', to: 'host_session#new'
  post '/loginhost', to: 'host_session#create'
  delete '/logouthost', to: 'host_session#destroy'
  
  #Static pages routes
  get '/home', to: 'static_pages#home'
  get '/works', to: 'static_pages#works'

  #Routes for dashboard
  # get '/dashboard', to: 'hosts#index' 
  
  

  

  #resources  :listings
  
  #resources  :hosts 
  
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/host.rb
class Host < ApplicationRecord

	has_many :workspaces

	validates :name, presence: true, length: { maximum: 50}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, presence: true, length: { maximum: 255 } , 
	                  format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: false }

    has_secure_password

    validates :password, presence: true, length: { minimum: 6}, allow_nil: true

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
 
 before_action :logged_in_host, only: [:edit, :update , :show]
 before_action :correct_host, only: [:edit, :update, :show]
 

  def index
  end


 def show
 	@host = Host.find(params[:id])
 end

  def new
  	@host = Host.new
  end
  
  def create
  	@host = Host.new(host_params)
  	if @host.save

       log_in @host
  		 redirect_to @host
       # render 'host/index'
      
  	else
  		render 'new'
   end
end
  
  def edit
  	@host = Host.find(params[:id])
  end
  
  def update
  	@host = Host.find(params[:id])
  	if @host.update_attributes(host_params)
  		flash[:success] = "Profile update"
  		redirect_to @host
  	else
  		render 'edit'
  	end
  end


  private 
  
  def host_params
  	params.require(:host).permit(:name,:email,:password,:password_confirmation)
  end
  
  def logged_in_host
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to loginhost_url
    end
end

def correct_host
  @host = Host.find(params[:id])
  redirect_to(root_url) unless current_host?(@host)
end

end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_dashboard.html.erb
   <div class="wrapper">
    <div class="sidebar" data-color="blue" data-image="assets/img/sidebar-5.jpg">

      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="/">
                    <img class="img-responsive" src="assets/img/logo-white.png" >
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <!-- <a href="index.html">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a> -->
                    <%= link_to host_path do %>
                       <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    <% end %>
                </li>
                <li>
                    <!-- <a href="listings.html">
                        <i class="pe-7s-map-2"></i>
                        <p>Listings</p>
                    </a> -->
                    <%= link_to list_path do %>
                         <i class="pe-7s-map-2"></i>
                         <p>Listings</p>
                   <% end %>
                </li>
                <li>
                    <a href="#">
                        <i class="pe-7s-note2"></i>
                        <p>View Bookings</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="pe-7s-cash"></i>
                        <p>Payments</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="pe-7s-config"></i>
                        <p>Account</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="pe-7s-help1"></i>
                        <p>Help</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dijispace</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-sm hidden-xs"></b>
                                    <!-- <span class="notification hidden-sm hidden-xs">5</span> -->
                  <p class="hidden-lg hidden-md">
                    5 Notifications
                    <b class="caret"></b>
                  </p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>
                        <li>
                           <a href="">
                                <i class="fa fa-search"></i>
                <p class="hidden-lg hidden-md">Search</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href="">
                               <p>Account</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                    Dropdown
                    <b class="caret"></b>
                  </p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                        </li>
                        <li>
                            <a href="#">
                                <p>Log out</p>
                            </a>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

app/views/hosts/_form.html.erb
   <%= form_for(@host) do |f| %>
         
    <%= f.label :name %>
    <%= f.text_field :name , class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email , class: 'form-control'   %>

    <%= f.label :password %>
    <%= f.password_field :password , class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation , class: 'form-control' %>
    <br>
    <%= f.submit :Submit , class: 'btn btn-primary btn-block'%>
    <p>Existing Host? <%= link_to "Log In" , loginhost_path%> </p>
<% end %> 

app/views/hosts/_listspace.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<!-- list -->
<!-- new_host_workspace_path -->
  <div class="container">
  	<div class="row">
  		<div class="col-md-6 col-md-offset-3">
  		<%= link_to 'List your space'  , list_path  , class: 'btn btn-primary btn-block' %>	
  		</div>
          <br>
      <br>
      <br>
      <br>
  		<div class="col-md-6 col-md-offset-3">
  			<%= link_to 'Update  space'  ,  edit_workspace_path  , class: 'btn btn-primary btn-block' %>
  		</div>
  	</div>

  	  
  </div>

app/views/hosts/index.html.erb
<<<<<<< HEAD


 <div class="container">
=======
  <div class="container">
>>>>>>> h_dashboard
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
        <%= link_to 'List your space'  , list_path  , class: 'btn btn-primary btn-block' %> 
        </div>
          <br>
      <br>
      <br>
      <br>
        <div class="col-md-6 col-md-offset-3">
            <%= link_to 'Update  space'  ,  edit_workspace_path  , class: 'btn btn-primary btn-block' %>
        </div>
    </div>

      
  </div>
<<<<<<< HEAD













<!-- list -->
<!-- new_host_workspace_path -->
 

<!-- {:action=>"edit", :controller=>"workspaces", :host_id => workspaces.host_id , :id=> workspaces.id} -->

 <!--  {:controller=>"workspaces", :action=>"show", :host_id => workspaces.host_id, :id => workspaces.id}  -->

  
=======
>>>>>>> h_dashboard

app/views/hosts/new.html.erb
 <nav class="navbar navbar-default navbar-custom navbar-fixed-top home">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to image_tag("logo.png" , class: "img-responsive"), root_path, class: "navbar-brand" %>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <!-- <a href="#">Register Your Space</a> -->
                    <%= link_to "Register Your Space" , signuphost_path%>
                </li>

                
                <% if logged_in? %>
                <li><%= link_to "Users", '#' %></li>
                    <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu"> 
                  <li><%= link_to "Profile", current_user%></li>
                  <li><%= link_to "Settings", "#"%></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log Out", logout_path, method: "delete" %>
                  </li>
                </ul>
            </li>
              <% else %>    
            
                    <li>
                          <%= link_to "Login" , login_path %>
                    </li>
                
                <li>
                         <%= link_to "Sign Up" , signup_path %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>






<br>
<section>
	<center><h1> </h1></center>
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				 <div class="panel panel-default  ">
					<div class="panel-heading">
						<strong> Register as a Host </strong>
					</div>
					<div class="panel-body">
						<%= render 'form' %>
					</div>
				
                </div>

			</div>
		</div>
	</div>
</section>

app/views/hosts/show.html.erb
<!-- list -->
<!-- new_host_workspace_path -->
 

<!-- {:action=>"edit", :controller=>"workspaces", :host_id => workspaces.host_id , :id=> workspaces.id} -->

 <!--  {:controller=>"workspaces", :action=>"show", :host_id => workspaces.host_id, :id => workspaces.id}  -->



    
 <%= render 'dashboard' %>

    <div class="page-content">
      <div class="wrapper">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Listings</h4>

                                <!-- <button type="submit" class="btn btn-info btn-fill pull-left">Add New</button> -->
                               <%= link_to "Add New" , list_path , class:"btn btn-info btn-fill pull-left" %>  
                             
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
                                    <thead>
                                        <th>ID</th>
                                      <th>Name</th>
                                      <th>Country</th>
                                      <th>City</th>
                                    </thead>
                                    <tbody>
                                        <tr>
                                          <td>1</td>
                                          <td>Dakota Rice</td>
                                          <td>Niger</td>
                                          <td>Oud-Turnhout</td>
                                        </tr>
                                        <tr>
                                          <td>2</td>
                                          <td>Minerva Hooper</td>
                                          <td>Curaçao</td>
                                          <td>Sinaai-Waas</td>
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
      </div>
    </div>
  